### ISSUE TITLE
APNS bundleId is deprecated, use topic instead

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-server-modules/parse-server-push-adapter#85] opened 2017-07-04 14:20 UTC
With the new release I saw this in my logs: `APNS bundleId is deprecated, use topic instead`. However I could not find anything about how to use `topic` in my configuration in the docs yet. I would love to see this covered as I will probably not be the only one with this issue.

**Comment by natanrolnik** [comment] 2017-07-04 14:42
Closing as duplicate of #83
As the warning says, just pass `topic` instead of `bundleId` in the adapters configuration.

**Closed by natanrolnik** 2017-07-04 14:42 UTC
Labels: question
